### ISSUE TITLE
Add geometry.hpp with core types

### ISSUE THREAD

**Issue by springmeyer** [mapbox/geometry.hpp#1]
We'll need:

  - coord_type: start with `double` for now 
  - point<coord_type> (aka LonLat)
  - linestring<point>
  - polygon<linear_ring>
  - multi types

**Comment by artemp** [comment]
Simplicity is a key!  OGC and boost::geometry compatible implementation  acb7587c3506e2f86a5d5d4198c2b23ec03b4be2 e5b79a19f9eb408c14cebd9147fc6ed306159014
/cc @kkaefer @jfirebaugh @mourner @flippmoke @springmeyer

**Comment by springmeyer** [comment]
Great start @artemp. Can we move the `geometry_base` (aka only usage that needs `variant` dep) to separate header make `variant` dep opt-in?

**Comment by artemp** [comment]
@springmeyer - this is just a start :). I guess you're thinking about re-arranging headers so all geometry types can be used standalone?  e.g 

```c++ 
#include <mapbox/util/geometry/point.hpp>
```  

This is on my TODO list

**Comment by mourner** [comment]
Splitted in https://github.com/mapbox/geometry.hpp/commit/052c0265cf12f864256c41467c9ed01af15435f6
