### ISSUE TITLE
Use std::alignas on point struct

### ISSUE THREAD

**Issue by flippmoke** [mapbox/geometry.hpp#15]
Can we be explicit about the memory alignment of the point struct as this could help in the future with operations such as SSE that might directly access the memory in the struct.

/cc @daniel-j-h

**Comment by jfirebaugh** [comment]
Can you be more specific as to what this would help with?

**Comment by mourner** [comment]
@flippmoke any updates here or can I close for now?

**Comment by flippmoke** [comment]
I think we can close for now -- this was due to a talk with @daniel-j-h about how we could possibly always guarantee the byte order of data in the geometry point struct. I am not sure this is critical, but we could just leave it open for discussion. @joto @artemp
