### ISSUE TITLE
Change std::nullptr_t to explicit null type

### ISSUE THREAD

**Issue by kkaefer** [mapbox/geometry.hpp#33]
Instead of using `std::nullptr_t`, we should use an explicit null type (like a ` struct null_value {};`). `std::string` has an overload that also accepts `std::nullptr_t`.

See https://github.com/mapbox/variant/issues/100

**Comment by artemp** [comment]
👍

**Comment by jfirebaugh** [comment]
The issue with this is that `value` will still be constructible or assignable with `nullptr`, but instead of being set to the null alternative as you might expect, it will segfault at runtime.

**Comment by kkaefer** [comment]
It segfaults because the std::string constructor is invoked with the nullptr.

**Comment by jfirebaugh** [comment]
My bad -- it does not segfault. It constructs a `value` where `bool` is the stored type and `false` is its value.

I would feel more comfortable with this change if we could fix https://github.com/mapbox/variant/issues/100, such that an ambiguous assignment from `nullptr` was an error.

**Comment by jfirebaugh** [comment]
I think #40 avoids those potential issues!
