### ISSUE TITLE
Provide the default constructor to Box

### ISSUE THREAD

**Issue by themics** [mapbox/geometry.hpp#35]
Due to the lack of default constructor, `Box` is not adaptable to some boost.geometry algorithm that  performs default initialization.

For instance, below code snippet from [`boost::geometry::return_envelope`](
http://www.boost.org/doc/libs/1_61_0/boost/geometry/algorithms/detail/envelope/interface.hpp), `mbr` is default initializated.

```c++
template<typename Box, typename Geometry>
inline Box return_envelope(Geometry const& geometry)
{
    Box mbr;
    resolve_variant::envelope<Geometry>::apply(geometry, mbr);
    return mbr;
}
```

Although we can still use output parameter version(`boost::geometry::envelope`) but it will be good if default constructor is provided.

**Comment by jfirebaugh** [comment]
Sorry, but compatibility with boost::geometry is not a design goal of this library. If there is some other compelling reason to add a default constructor we can consider it, but by default I prefer to avoid having an "invalid" or "empty" state where possible.
