### ISSUE TITLE
Add Null Geometry

### ISSUE THREAD

**Issue by flippmoke** [mapbox/geometry.hpp#44]
I believe that we should add a null geometry type. I know that this is could be viewed as a major change, but I believe it is an important thing for us to consider. Take for example a clipping algorithm that returns a `geometry` type and takes a`geometry` as input. 

What happens if there is nothing to return?

For multipoints, lines, and polygons this is all very simple in that we could provide back an empty array, but is this really a great idea? This means that later on in processing we must do validity checks on all types of geometry to make sure they are actually valid. This can add extra processing that might not be necessary, as well as a lot of extra code.

Then there is the case of a point, what happens if you are clipping a point and it is not within the bounds of your clip? You could set it to a point that is `{ NaN, NaN }` but this seems like a very hack-ish thing to do as well. I believe we should consider adding a fully featured null geometry - it will make it much easier to handle properly.

Another option could perhaps be to add a null type to variants as a feature, such that variants and visitors could simply know to do nothing null options? This might remove a lot of extra code blot from visitors due to null types, however, it could add quite a bit of overhead complexity.

**Comment by jfirebaugh** [comment]
My (fairly strongly held) opinion is that algorithms that need the ability to represent a "null" result should use [`std::optional<geometry>`](http://en.cppreference.com/w/cpp/utility/optional), [`std::experimental::optional<geometry>`](http://en.cppreference.com/w/cpp/experimental/optional), or [`mapbox::util::optional<geometry>`](https://github.com/mapbox/variant/blob/master/include/mapbox/optional.hpp), depending on what revision of the C++ standard they target.

This limits the need to explicitly handle a null geometry to those use cases that actually require it. 
The alternative of adding an explicit null type to the `geometry_base` variant list means that every geometry algorithm (whether defined in this library or in application code) must be prepared to cope with null geometries. This adds significant complexity and corner cases to virtually all algorithms. The complexity is not confined to the algorithm implementations either -- every algorithm consumer must also implement some form of error handling to deal with the possibility of a null result.
