### ISSUE TITLE
mutating methods

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/geometry.hpp#7]
What's the rationale for having:

* `line_string::add_coord`
* `polygon::set_exterior_ring`
* `polygon::add_hole`

Should the base types even expose any built-in mutating methods?

**Comment by artemp** [comment]
@jfirebaugh - the only rational is trying to be nice to the user and attempting to have somewhat meaningful names - ref: https://github.com/mapnik/mapnik/blob/master/src/twkb.cpp

**Comment by jfirebaugh** [comment]
My preference is to keep the geometry types (except for `point`) ultra-minimal "strong typedefs" to their base container type. E.g.:

```C++
template <typename T, template <typename...> class container = std::vector>
struct line_string : container<point<T>>
{
    using container_type = container<point<T>>;
    using container_type::container_type;
};
```

Auxiliary methods can be defined as standalone functions in the `mapbox::geometry` namespace. (I'm not sure that geometry.hpp itself should define any though. Can we leave this up to other libraries?)

This would avoid needing to make case-by-case design decisions about what auxiliary methods merit being defined as instance methods.

**Comment by artemp** [comment]
@jfirebaugh - Yes, we can.

**Comment by artemp** [comment]
@jfirebaugh - having second thoughts:)  While I agree that algorithms and/or any application specific methods should be left out, basic interface for creating geometries will encourage `correct` usage! Also every single library will have to implement pretty much the same set of methods - this strikes me as a not fair design. And there's no performance penalty for having one. 

Having this minimal interface is not stopping someone implementing its own. though.  I prefer "if you really want to do it, you know how and what are the implications" approach.  

/cc @springmeyer @kkaefer @flippmoke

**Comment by artemp** [comment]
@jfirebaugh - #9 splits geometry into pure data structures and basic interface and flexible enough for general usage across projects 

/cc @springmeyer @flippmoke @daniel-j-h @danpat @kkaefer

**Comment by jfirebaugh** [comment]
I removed these in c53598de7cb5d207ce8099f6e3270f8d68287e5d, but we can revisit this as we start to use geometry.hpp in downstream projects.
