### ISSUE TITLE
features

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/geometry.hpp#8]
Several use cases for this library will also require a feature representation: geometry plus properties.

A basic sketch of the necessary types would be:

```C++
using value = mapbox::util::variant<bool, int64_t, uint64_t, double, std::string>;
using property_map = std::unordered_map<std::string, value>;

template <class T>
struct feature
{
    property_map properties;
    geometry<T> geometry;
};

template <class T, template <typename...> class collection>
struct feature_collection : collection<feature<T>>
{
    using collection_type = collection<feature<T>>;
    using collection_type::collection_type;
};
```

**Comment by ansis** [comment]
Should object and array properties be supported?
Or would json arrays be stored in stringified form?
slightly related: https://github.com/mapbox/mapbox-gl-js/issues/2434

**Comment by artemp** [comment]
@ansis - we can and should store recursive types via `variant::recursive_wrapper<T>` 
@jfirebaugh - `feature` sketch looks like a good start. I'm wondering why distinguish between signed and unsigned, though? /cc @kkaefer ?

**Comment by jfirebaugh** [comment]
@artemp The JSON specification does not limit the size of integers, so it's useful to expose both signed and unsigned 64-bit integers to cover the widest possible range. This also follows the [vector tile spec](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L24-L26), [existing convention in mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/blob/a392f972fca0e8d7bedbda8a7fe6410567682195/src/mbgl/style/value.hpp#L12), and what rapidjson exposes.
